### ISSUE TITLE
Golden Core and Advancement Missing Texture 

### ISSUE THREAD

**Issue by spinner899** [Craftjakob/Gilded-Armor#2]
As title describes, the golden core and it's advancement appear as a missing texture. See attached pictures.
Playing on Fabric 1.21.4 and downloaded the mod through Modrinth.

![Golden Core Advancement Missing](https://github.com/user-attachments/assets/f0c8f07b-cd64-4ff9-a750-b58d2faf5bf1)
![Golden Core Missing Texture](https://github.com/user-attachments/assets/02b89711-f03d-4ffe-9fe1-8bd71581734a)

**Comment by Craftjakob** [comment]
Yes, you are right, the texture is not shown, I have now fixed it. You need to install the newest version, which is available in a few minutes.

**Comment by Craftjakob** [comment]
And thanks for the report!
